## Imports and Declarations

In [1]:
import pandas as pd
import numpy as np
import torch
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from transformers import AutoTokenizer, AutoModel
from sklearn.feature_extraction.text import TfidfVectorizer

/opt/anaconda3/envs/lumaa/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
#search_sentence = "I love thrilling action movies set in space, with a comedic twist."
#search_sentence = "I love movies based on gangster, cartels and crime that have drama and action in it with great storyline"
search_sentence = "I love coming of age movies with a comedic twist."

In [3]:
tfidf = TfidfVectorizer()
bert_model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(bert_model_name)
model = AutoModel.from_pretrained(bert_model_name)

In [4]:
nltk.download('wordnet')
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/ritamupadhyay/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [5]:
top_k_matches = 5

## Data Import

### Data Set is available at https://www.kaggle.com/datasets/adikhare/top-100-imdb-movies

In [6]:
df = pd.read_csv('data/Top 100 IMDB Movies.csv')

In [7]:
df

,rank,title,description,image,big_image,genre,thumbnail,rating,id,year,imdbid,imdb_link
0,1,The Shawshank Redemption,Two imprisoned men bond over a number of years...,https://m.media-amazon.com/images/M/MV5BMDFkYT...,https://m.media-amazon.com/images/M/MV5BMDFkYT...,['Drama'],https://m.media-amazon.com/images/M/MV5BMDFkYT...,9.3,top1,1994,tt0111161,https://www.imdb.com/title/tt0111161
1,2,The Godfather,The aging patriarch of an organized crime dyna...,https://m.media-amazon.com/images/M/MV5BM2MyNj...,https://m.media-amazon.com/images/M/MV5BM2MyNj...,"['Crime', 'Drama']",https://m.media-amazon.com/images/M/MV5BM2MyNj...,9.2,top2,1972,tt0068646,https://www.imdb.com/title/tt0068646
2,3,The Dark Knight,When the menace known as the Joker wreaks havo...,https://m.media-amazon.com/images/M/MV5BMTMxNT...,https://m.media-amazon.com/images/M/MV5BMTMxNT...,"['Action', 'Crime', 'Drama']",https://m.media-amazon.com/images/M/MV5BMTMxNT...,9.0,top3,2008,tt0468569,https://www.imdb.com/title/tt0468569
3,4,The Godfather Part II,The early life and career of Vito Corleone in ...,https://m.media-amazon.com/images/M/MV5BMWMwMG...,https://m.media-amazon.com/images/M/MV5BMWMwMG...,"['Crime', 'Drama']",https://m.media-amazon.com/images/M/MV5BMWMwMG...,9.0,top4,1974,tt0071562,https://www.imdb.com/title/tt0071562
4,5,12 Angry Men,The jury in a New York City murder trial is fr...,https://m.media-amazon.com/images/M/MV5BMWU4N2...,https://m.media-amazon.com/images/M/MV5BMWU4N2...,"['Crime', 'Drama']",https://m.media-amazon.com/images/M/MV5BMWU4N2...,9.0,top5,1957,tt0050083,https://www.imdb.com/title/tt0050083
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Reservoir Dogs,When a simple jewelry heist goes horribly wron...,https://m.media-amazon.com/images/M/MV5BZmExNm...,https://m.media-amazon.com/images/M/MV5BZmExNm...,"['Crime', 'Thriller']",https://m.media-amazon.com/images/M/MV5BZmExNm...,8.3,top96,1992,tt0105236,https://www.imdb.com/title/tt0105236
96,97,Ikiru,A bureaucrat tries to find meaning in his life...,https://m.media-amazon.com/images/M/MV5BYWM1Ym...,https://m.media-amazon.com/images/M/MV5BYWM1Ym...,['Drama'],https://m.media-amazon.com/images/M/MV5BYWM1Ym...,8.3,top97,1952,tt0044741,https://www.imdb.com/title/tt0044741
97,98,Lawrence of Arabia,"The story of T.E. Lawrence, the English office...",https://m.media-amazon.com/images/M/MV5BYWY5Zj...,https://m.media-amazon.com/images/M/MV5BYWY5Zj...,"['Adventure', 'Biography', 'Drama']",https://m.media-amazon.com/images/M/MV5BYWY5Zj...,8.3,top98,1962,tt0056172,https://www.imdb.com/title/tt0056172
98,99,Citizen Kane,Following the death of publishing tycoon Charl...,https://m.media-amazon.com/images/M/MV5BYjBiOT...,https://m.media-amazon.com/images/M/MV5BYjBiOT...,"['Drama', 'Mystery']",https://m.media-amazon.com/images/M/MV5BYjBiOT...,8.3,top99,1941,tt0033467,https://www.imdb.com/title/tt0033467
99,100,M,When the police in a German city are unable to...,https://m.media-amazon.com/images/M/MV5BODA4OD...,https://m.media-amazon.com/images/M/MV5BODA4OD...,"['Crime', 'Mystery', 'Thriller']",https://m.media-amazon.com/images/M/MV5BODA4OD...,8.3,top100,1931,tt0022100,https://www.imdb.com/title/tt0022100

In [8]:
for i in np.random.randint(0, 10, size=5):
    print(df.iloc[i]['title']," ",df.iloc[i]['description'])

Pulp Fiction   The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.
Schindler's List   In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.
The Lord of the Rings: The Fellowship of the Ring   A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.
Pulp Fiction   The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.
The Lord of the Rings: The Fellowship of the Ring   A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.

## Data Transform

In [9]:
## Idea is to add the genre and date of release in the description
release_date = " The movie was released in the year "
genre = " The genre is of "
def add_date_genre(x):
    return x['description']+release_date+str(x['year'])+'.'+genre+' and '.join(eval(x['genre']))

In [10]:
df['description_2'] = df.apply(lambda x: add_date_genre(x),axis=1)

In [11]:
## Print few descriptions to check the append of genre and release date
for i in np.random.randint(0, 10, size=5):
    print(df.iloc[i]['title']," ",df.iloc[i]['description_2'])

The Shawshank Redemption   Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. The movie was released in the year 1994. The genre is of Drama
The Good, the Bad and the Ugly   A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery. The movie was released in the year 1966. The genre is of Adventure and Western
The Shawshank Redemption   Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. The movie was released in the year 1994. The genre is of Drama
The Lord of the Rings: The Fellowship of the Ring   A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron. The movie was released in the year 2001. The genre is of Action and Adventure and Drama
The Good, the Bad and the Ugly   A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery. The movie was released in the year 1966. The genre is of Adventure and Western

In [12]:
## Stemming and Lemmetizing the corpus and search query
def preprocess(text):
    words = text.split()
    stemmed_words = [stemmer.stem(word) for word in words]  # Apply stemming first
    lemmatized_words = [lemmatizer.lemmatize(word) for word in stemmed_words]  # Apply lemmatization
    return " ".join(lemmatized_words)

In [13]:
df['description_final'] = df.apply(lambda x: preprocess(x['description_2']),axis=1)
search_sentence_final = preprocess(search_sentence)

In [14]:
## Print few descriptions to check the stemm and lemmetization
for i in np.random.randint(0, 10, size=5):
    print(df.iloc[i]['title']," ",df.iloc[i]['description_final'])

12 Angry Men   the juri in a new york citi murder trial is frustrat by a singl member whose skeptic caution forc them to more care consid the evid befor jump to a hasti verdict. the movi wa releas in the year 1957. the genr is of crime and drama
The Shawshank Redemption   two imprison men bond over a number of years, find solac and eventu redempt through act of common decency. the movi wa releas in the year 1994. the genr is of drama
The Lord of the Rings: The Fellowship of the Ring   a meek hobbit from the shire and eight companion set out on a journey to destroy the power one ring and save middle-earth from the dark lord sauron. the movi wa releas in the year 2001. the genr is of action and adventur and drama
Schindler's List   in german-occupi poland dure world war ii, industrialist oskar schindler gradual becom concern for hi jewish workforc after wit their persecut by the nazis. the movi wa releas in the year 1993. the genr is of biographi and drama and histori
The Lord of the Rings: The Return of the King   gandalf and aragorn lead the world of men against sauron' armi to draw hi gaze from frodo and sam a they approach mount doom with the one ring. the movi wa releas in the year 2003. the genr is of action and adventur and drama

In [15]:
## Calculate TFIDF
tfidf_matrix = tfidf.fit_transform(df['description_final'].to_list()+[search_sentence_final])
word2tfidf = dict(zip(tfidf.get_feature_names_out(), tfidf.idf_))

In [16]:
## Got the tfidf score of each word in corpus
word2tfidf

{'000': np.float64(4.931825632724326),
 '10': np.float64(4.931825632724326),
 '12': np.float64(4.526360524616162),
 '17': np.float64(4.931825632724326),
 '1890': np.float64(4.931825632724326),
 '1920': np.float64(4.526360524616162),
 '1931': np.float64(4.526360524616162),
 '1936': np.float64(4.931825632724326),
 '1940': np.float64(4.931825632724326),
 '1941': np.float64(4.931825632724326),
 '1942': np.float64(4.931825632724326),
 '1946': np.float64(4.931825632724326),
 '1950': np.float64(4.931825632724326),
 '1952': np.float64(4.526360524616162),
 '1954': np.float64(4.526360524616162),
 '1957': np.float64(4.238678452164381),
 '1960': np.float64(4.931825632724326),
 '1962': np.float64(4.526360524616162),
 '1963': np.float64(4.526360524616162),
 '1964': np.float64(4.931825632724326),
 '1966': np.float64(4.931825632724326),
 '1968': np.float64(4.526360524616162),
 '1972': np.float64(4.931825632724326),
 '1974': np.float64(4.931825632724326),
 '1975': np.float64(4.931825632724326),
 '1977': np.float64(4.931825632724326),
 '1979': np.float64(4.526360524616162),
 '1980': np.float64(4.526360524616162),
 '1981': np.float64(4.526360524616162),
 '1983': np.float64(4.931825632724326),
 '1984': np.float64(4.238678452164381),
 '1985': np.float64(4.526360524616162),
 '1986': np.float64(4.931825632724326),
 '1988': np.float64(4.526360524616162),
 '1990': np.float64(4.931825632724326),
 '1991': np.float64(4.526360524616162),
 '1992': np.float64(4.931825632724326),
 '1993': np.float64(4.931825632724326),
 '1994': np.float64(3.6790626642289577),
 '1995': np.float64(4.01553490085017),
 '1997': np.float64(4.238678452164381),
 '1998': np.float64(4.526360524616162),
 '1999': np.float64(4.01553490085017),
 '2000': np.float64(4.238678452164381),
 '2001': np.float64(4.526360524616162),
 '2002': np.float64(4.238678452164381),
 '2003': np.float64(4.526360524616162),
 '2004': np.float64(4.931825632724326),
 '2006': np.float64(4.526360524616162),
 '2008': np.float64(4.526360524616162),
 '2009': np.float64(4.526360524616162),
 '2010': np.float64(4.526360524616162),
 '2011': np.float64(4.931825632724326),
 '2012': np.float64(4.238678452164381),
 '2014': np.float64(4.526360524616162),
 '2016': np.float64(4.931825632724326),
 '2017': np.float64(4.931825632724326),
 '2018': np.float64(4.01553490085017),
 '2019': np.float64(4.238678452164381),
 '2023': np.float64(4.526360524616162),
 '30': np.float64(4.931825632724326),
 '35': np.float64(4.931825632724326),
 '40': np.float64(4.931825632724326),
 '75': np.float64(4.931825632724326),
 '9000': np.float64(4.931825632724326),
 'abandon': np.float64(4.931825632724326),
 'abil': np.float64(4.931825632724326),
 'abl': np.float64(4.931825632724326),
 'aboard': np.float64(4.931825632724326),
 'about': np.float64(4.526360524616162),
 'absorb': np.float64(4.931825632724326),
 'accept': np.float64(4.931825632724326),
 'accident': np.float64(4.238678452164381),
 'accumul': np.float64(4.931825632724326),
 'accus': np.float64(4.526360524616162),
 'across': np.float64(4.526360524616162),
 'act': np.float64(4.931825632724326),
 'action': np.float64(2.366876275262789),
 'addict': np.float64(4.931825632724326),
 'adenoid': np.float64(4.931825632724326),
 'admit': np.float64(4.931825632724326),
 'advanc': np.float64(4.931825632724326),
 'adventur': np.float64(2.2927683031090673),
 'affect': np.float64(4.931825632724326),
 'after': np.float64(2.734601055388106),
 'again': np.float64(4.931825632724326),
 'against': np.float64(3.545531271604435),
 'age': np.float64(4.526360524616162),
 'agent': np.float64(4.931825632724326),
 'aid': np.float64(4.931825632724326),
 'alabama': np.float64(4.931825632724326),
 'all': np.float64(4.238678452164381),
 'alli': np.float64(4.931825632724326),
 'allianc': np.float64(4.931825632724326),
 'allies': np.float64(4.931825632724326),
 'ally': np.float64(4.931825632724326),
 'also': np.float64(4.526360524616162),
 'amadeu': np.float64(4.931825632724326),
 'american': np.float64(4.01553490085017),
 'an': np.float64(2.329135947279942),
 'anarchy': np.float64(4.931825632724326),
 'ancestr': np.float64(4.931825632724326),
 'and': np.float64(1.0606246218164348),
 'andi': np.float64(4.931825632724326),
 'angel': np.float64(4.931825632724326),
 'anim': np.float64(3.1400661634962708),
 'anoth': np.float64(4.526360524616162),
 'antonio': np.float64(4.931825632724326),
 'anyon': np.float64(4.931825632724326),
 'apart': np.float64(4.526360524616162),
 'apocalypt': np.float64(4.931825632724326),
 'approach': np.float64(4.931825632724326),
 'arab': np.float64(4.931825632724326),
 'aragorn': np.float64(4.931825632724326),
 'archaeolog': np.float64(4.931825632724326),
 'are': np.float64(3.1400661634962708),
 'aristocrat': np.float64(4.931825632724326),
 'ark': np.float64(4.931825632724326),
 'armi': np.float64(4.238678452164381),
 'around': np.float64(4.931825632724326),
 'artefact': np.float64(4.931825632724326),
 'artifact': np.float64(4.931825632724326),
 'ascend': np.float64(4.931825632724326),
 'ashitaka': np.float64(4.931825632724326),
 'aspir': np.float64(4.931825632724326),
 'assassin': np.float64(4.01553490085017),
 'assembl': np.float64(4.931825632724326),
 'at': np.float64(3.833213344056216),
 'atlant': np.float64(4.931825632724326),
 'atom': np.float64(4.931825632724326),
 'attack': np.float64(4.01553490085017),
 'attempt': np.float64(3.833213344056216),
 'attic': np.float64(4.931825632724326),
 'aveng': np.float64(4.526360524616162),
 'avengers': np.float64(4.931825632724326),
 'avoid': np.float64(4.931825632724326),
 'awaken': np.float64(4.931825632724326),
 'back': np.float64(4.931825632724326),
 'balanc': np.float64(4.931825632724326),
 'ban': np.float64(4.931825632724326),
 'bandit': np.float64(4.526360524616162),
 'bandits': np.float64(4.931825632724326),
 'bane': np.float64(4.931825632724326),
 'barber': np.float64(4.931825632724326),
 'barrist': np.float64(4.931825632724326),
 'batman': np.float64(4.526360524616162),
 'battl': np.float64(4.238678452164381),
 'be': np.float64(3.4277482359480516),
 'beasts': np.float64(4.931825632724326),
 'beauti': np.float64(4.526360524616162),
 'becom': np.float64(3.2270775404859005),
 'bedroom': np.float64(4.931825632724326),
 'been': np.float64(4.526360524616162),
 'befor': np.float64(4.238678452164381),
 'began': np.float64(4.931825632724326),
 'begin': np.float64(4.526360524616162),
 'behind': np.float64(4.931825632724326),
 'beneath': np.float64(4.931825632724326),
 'berlin': np.float64(4.931825632724326),
 'best': np.float64(4.931825632724326),
 'better': np.float64(4.931825632724326),
 'between': np.float64(4.526360524616162),
 'biblic': np.float64(4.931825632724326),
 'biographi': np.float64(3.4277482359480516),
 'bitter': np.float64(4.931825632724326),
 'bizarr': np.float64(4.931825632724326),
 'black': np.float64(4.931825632724326),
 'blitz': np.float64(4.931825632724326),
 'boat': np.float64(4.526360524616162),
 'boba': np.float64(4.931825632724326),
 'bomb': np.float64(4.526360524616162),
 'bond': np.float64(4.931825632724326),
 'boston': np.float64(4.931825632724326),
 'both': np.float64(4.931825632724326),
 'bound': np.float64(4.931825632724326),
 'bounti': np.float64(4.526360524616162),
 'bounty': np.float64(4.931825632724326),
 'boxer': np.float64(4.931825632724326),
 'boy': np.float64(4.01553490085017),
 'british': np.float64(4.931825632724326),
 'brother': np.float64(4.526360524616162),
 'brown': np.float64(4.931825632724326),
 'brutal': np.float64(3.833213344056216),
 'bureaucrat': np.float64(4.931825632724326),
 'buri': np.float64(4.526360524616162),
 'businessman': np.float64(4.931825632724326),
 'but': np.float64(4.238678452164381),
 'by': np.float64(2.6292405397302803),
 'cadet': np.float64(4.931825632724326),
 'cafe': np.float64(4.931825632724326),
 'call': np.float64(4.931825632724326),
 'camp': np.float64(4.931825632724326),
 'cancer': np.float64(4.931825632724326),
 'cannib': np.float64(4.931825632724326),
 'captor': np.float64(4.931825632724326),
 'car': np.float64(4.526360524616162),
 'care': np.float64(4.931825632724326),
 'career': np.float64(4.931825632724326),
 'caregiver': np.float64(4.931825632724326),
 'catapult': np.float64(4.931825632724326),
 'catch': np.float64(4.526360524616162),
 'caution': np.float64(4.931825632724326),
 'cemetery': np.float64(4.931825632724326),
 'center': np.float64(4.931825632724326),
 'challeng': np.float64(4.931825632724326),
 'chang': np.float64(4.931825632724326),
 'chao': np.float64(4.931825632724326),
 'charg': np.float64(4.931825632724326),
 'charges': np.float64(4.931825632724326),
 'charl': np.float64(4.931825632724326),
 'chauffeur': np.float64(4.931825632724326),
 'check': np.float64(4.931825632724326),
 'child': np.float64(4.526360524616162),
 'childhood': np.float64(4.526360524616162),
 'choru': np.float64(4.931825632724326),
 'cinema': np.float64(4.931825632724326),
 'citi': np.float64(3.833213344056216),
 'claim': np.float64(4.931825632724326),
 'clan': np.float64(4.526360524616162),
 'clandestin': np.float64(4.931825632724326),
 'clash': np.float64(4.931825632724326),
 'class': np.float64(4.931825632724326),
 'claustrophob': np.float64(4.931825632724326),
 'client': np.float64(4.526360524616162),
 'close': np.float64(4.931825632724326),
 'closer': np.float64(4.931825632724326),
 'club': np.float64(4.931825632724326),
 'cocki': np.float64(4.931825632724326),
 'coincid': np.float64(4.931825632724326),
 'collect': np.float64(4.931825632724326),
 'colleg': np.float64(4.931825632724326),
 'college': np.float64(4.931825632724326),
 'colonel': np.float64(4.931825632724326),
 'colony': np.float64(4.931825632724326),
 'come': np.float64(4.931825632724326),
 'comed': np.float64(4.931825632724326),
 'comedi': np.float64(3.0600234558227344),
 'comedian': np.float64(4.931825632724326),
 'command': np.float64(4.931825632724326),
 'commerci': np.float64(4.931825632724326),
 'commit': np.float64(4.931825632724326),
 'common': np.float64(4.931825632724326),
 'compani': np.float64(4.931825632724326),
 'companion': np.float64(4.526360524616162),
 'compos': np.float64(4.931825632724326),
 'comput': np.float64(4.931825632724326),
 'concern': np.float64(4.931825632724326),
 'conduct': np.float64(4.931825632724326),
 'coney': np.float64(4.931825632724326),
 'confront': np.float64(4.526360524616162),
 'connect': np.float64(4.931825632724326),
 'connor': np.float64(4.931825632724326),
 'conservatori': np.float64(4.931825632724326),
 'consid': np.float64(4.931825632724326),
 'contemporan': np.float64(4.931825632724326),
 'control': np.float64(4.931825632724326),
 'convinc': np.float64(4.526360524616162),
 'conway': np.float64(4.931825632724326),
 'cop': np.float64(4.931825632724326),
 'corleon': np.float64(4.931825632724326),
 'corpor': np.float64(4.931825632724326),
 'corrupt': np.float64(4.931825632724326),
 'countryman': np.float64(4.931825632724326),
 'coupl': np.float64(4.931825632724326),
 'courtyard': np.float64(4.931825632724326),
 'covenant': np.float64(4.931825632724326),
 'cover': np.float64(4.931825632724326),
 'cowardic': np.float64(4.931825632724326),
 'cowboy': np.float64(4.931825632724326),
 'creat': np.float64(4.931825632724326),
 'creation': np.float64(4.931825632724326),
 'creatures': np.float64(4.931825632724326),
 'crew': np.float64(4.526360524616162),
 'crime': np.float64(2.5339303599259555),
 'crimin': np.float64(4.01553490085017),
 'crisi': np.float64(4.931825632724326),
 'cure': np.float64(4.931825632724326),
 'curse': np.float64(4.931825632724326),
 'custody': np.float64(4.931825632724326),
 'cut': np.float64(4.931825632724326),
 'cyber': np.float64(4.931825632724326),
 'cyborg': np.float64(4.931825632724326),
 'cynic': np.float64(4.931825632724326),
 'dae': np.float64(4.931825632724326),
 'danger': np.float64(4.526360524616162),
 'dare': np.float64(4.931825632724326),
 'dark': np.float64(4.526360524616162),
 'darth': np.float64(4.238678452164381),
 'daughter': np.float64(4.931825632724326),
 'day': np.float64(4.526360524616162),
 'days': np.float64(4.931825632724326),
 'dead': np.float64(4.931825632724326),
 'deadli': np.float64(4.526360524616162),
 'death': np.float64(4.238678452164381),
 'decency': np.float64(4.931825632724326),
 'decept': np.float64(4.931825632724326),
 'decid': np.float64(4.526360524616162),
 'deep': np.float64(4.526360524616162),
 'defeat': np.float64(4.931825632724326),
 'defend': np.float64(4.238678452164381),
 'deliv': np.float64(4.931825632724326),
 'delorean': np.float64(4.931825632724326),
 'delusion': np.float64(4.931825632724326),
 'desir': np.float64(4.931825632724326),
 'desper': np.float64(4.931825632724326),
 'desperado': np.float64(4.931825632724326),
 'despit': np.float64(4.931825632724326),
 'destitut': np.float64(4.931825632724326),
 'destroy': np.float64(4.238678452164381),
 'destruct': np.float64(4.931825632724326),
 'detectives': np.float64(4.931825632724326),
 'determin': np.float64(4.931825632724326),
 'devast': np.float64(4.526360524616162),
 'develop': np.float64(4.526360524616162),
 'devil': np.float64(4.931825632724326),
 'devito': np.float64(4.931825632724326),
 'dewy': np.float64(4.931825632724326),
 'dictat': np.float64(4.931825632724326),
 'did': np.float64(4.931825632724326),
 'differently': np.float64(4.931825632724326),
 'difficult': np.float64(4.931825632724326),
 'dimens': np.float64(4.931825632724326),
 'diner': np.float64(4.931825632724326),
 'direct': np.float64(4.931825632724326),
 'disaster': np.float64(4.931825632724326),
 'discov': np.float64(4.526360524616162),
 'discrimin': np.float64(4.931825632724326),
 'dispatch': np.float64(4.931825632724326),
 'distanc': np.float64(4.931825632724326),
 'distant': np.float64(4.931825632724326),
 'diverg': np.float64(4.931825632724326),
 'diverse': np.float64(4.931825632724326),
 'divid': np.float64(4.931825632724326),
 'do': np.float64(4.526360524616162),
 'doc': np.float64(4.931825632724326),
 'doll': np.float64(4.931825632724326),
 'domin': np.float64(4.931825632724326),
 'doom': np.float64(4.526360524616162),
 'down': np.float64(4.526360524616162),
 'downward': np.float64(4.931825632724326),
 'drama': np.float64(1.3622929362429557),
 'draw': np.float64(4.931825632724326),
 'dream': np.float64(4.526360524616162),
 'droid': np.float64(4.931825632724326),
 'drug': np.float64(4.931825632724326),
 'drummer': np.float64(4.931825632724326),
 'dure': np.float64(3.833213344056216),
 'dynasti': np.float64(4.931825632724326),
 'each': np.float64(4.238678452164381),
 'earli': np.float64(4.931825632724326),
 'earth': np.float64(4.931825632724326),
 'east': np.float64(4.526360524616162),
 'edg': np.float64(4.931825632724326),
 'edward': np.float64(4.931825632724326),
 'eight': np.float64(4.526360524616162),
 'elabor': np.float64(4.931825632724326),
 'embark': np.float64(4.526360524616162),
 'embezzl': np.float64(4.931825632724326),
 'emperor': np.float64(4.526360524616162),
 'empir': np.float64(4.238678452164381),
 'empire': np.float64(4.931825632724326),
 'employer': np.float64(4.931825632724326),
 'encount': np.float64(4.526360524616162),
 'end': np.float64(4.931825632724326),
 'endor': np.float64(4.931825632724326),
 'enemi': np.float64(4.526360524616162),
 'engag': np.float64(4.931825632724326),
 'england': np.float64(4.931825632724326),
 'english': np.float64(4.931825632724326),
 'enigmat': np.float64(4.931825632724326),
 'enrol': np.float64(4.931825632724326),
 'ensur': np.float64(4.931825632724326),
 'enter': np.float64(4.931825632724326),
 'era': np.float64(4.526360524616162),
 'errat': np.float64(4.931825632724326),
 'escap': np.float64(4.931825632724326),
 'even': np.float64(4.931825632724326),
 'event': np.float64(4.238678452164381),
 'eventu': np.float64(4.931825632724326),
 'everyth': np.float64(4.931825632724326),
 'evid': np.float64(4.931825632724326),
 'evil': np.float64(4.931825632724326),
 'evolv': np.float64(4.931825632724326),
 'exact': np.float64(4.931825632724326),
 'execut': np.float64(4.931825632724326),
 'exil': np.float64(4.931825632724326),
 'existed': np.float64(4.931825632724326),
 'existence': np.float64(4.931825632724326),
 'expand': np.float64(4.526360524616162),
 'expatri': np.float64(4.931825632724326),
 'experi': np.float64(4.526360524616162),
 'exploit': np.float64(4.931825632724326),
 'explor': np.float64(4.931825632724326),
 'extort': np.float64(4.931825632724326),
 'ey': np.float64(4.931825632724326),
 'fade': np.float64(4.931825632724326),
 'fail': np.float64(4.931825632724326),
 'fall': np.float64(4.01553490085017),
 'fallen': np.float64(4.931825632724326),
 'famili': np.float64(3.4277482359480516),
 'family': np.float64(4.526360524616162),
 'fantasi': np.float64(3.6790626642289577),
 'farmer': np.float64(4.931825632724326),
 'fashion': np.float64(4.931825632724326),
 'fate': np.float64(4.931825632724326),
 'father': np.float64(4.238678452164381),
 'fellowship': np.float64(4.931825632724326),
 'fett': np.float64(4.931825632724326),
 'feudal': np.float64(4.931825632724326),
 'fi': np.float64(3.1400661634962708),
 'fifteen': np.float64(4.931825632724326),
 'fifty': np.float64(4.931825632724326),
 'fight': np.float64(4.01553490085017),
 'figur': np.float64(4.931825632724326),
 'film': np.float64(4.526360524616162),
 'filmmak': np.float64(4.931825632724326),
 'final': np.float64(4.931825632724326),
 'find': np.float64(3.0600234558227344),
 'five': np.float64(4.01553490085017),
 'flower': np.float64(4.931825632724326),
 'follow': np.float64(4.526360524616162),
 'for': np.float64(2.916922612182061),
 'forbid': np.float64(4.931825632724326),
 'forc': np.float64(3.6790626642289577),
 'forebod': np.float64(4.931825632724326),
 'forest': np.float64(4.931825632724326),
 'form': np.float64(4.01553490085017),
 'former': np.float64(4.01553490085017),
 'forms': np.float64(4.931825632724326),
 'fortun': np.float64(4.931825632724326),
 'foster': np.float64(4.931825632724326),
 'four': np.float64(4.526360524616162),
 'franc': np.float64(4.931825632724326),
 'frantic': np.float64(4.931825632724326),
 'free': np.float64(4.931825632724326),
 'freed': np.float64(4.931825632724326),
 'french': np.float64(4.931825632724326),
 'friend': np.float64(4.01553490085017),
 'friendship': np.float64(4.931825632724326),
 'frigid': np.float64(4.931825632724326),
 'frodo': np.float64(4.526360524616162),
 'from': np.float64(2.4060969884160706),
 'frustrat': np.float64(4.238678452164381),
 'fugit': np.float64(4.931825632724326),
 'full': np.float64(4.931825632724326),
 'future': np.float64(4.526360524616162),
 'galaxi': np.float64(4.526360524616162),
 'gandalf': np.float64(4.931825632724326),
 'gang': np.float64(4.931825632724326),
 'gangster': np.float64(4.526360524616162),
 'gather': np.float64(4.931825632724326),
 'gaze': np.float64(4.931825632724326),
 'gener': np.float64(4.238678452164381),
 'genr': np.float64(1.0098522964430117),
 'german': np.float64(3.833213344056216),
 'get': np.float64(4.931825632724326),
 'ghetto': np.float64(4.931825632724326),
 'ghost': np.float64(4.931825632724326),
 'gift': np.float64(4.526360524616162),
 'girl': np.float64(4.238678452164381),
 'girlfriend': np.float64(4.931825632724326),
 'given': np.float64(4.931825632724326),
 'go': np.float64(4.526360524616162),
 'god': np.float64(4.526360524616162),
 'gods': np.float64(4.931825632724326),
 'goe': np.float64(4.526360524616162),
 'gold': np.float64(4.931825632724326),
 'gollum': np.float64(4.931825632724326),
 'good': np.float64(4.931825632724326),
 'gotham': np.float64(4.526360524616162),
 'gradual': np.float64(4.931825632724326),
 'grandfather': np.float64(4.931825632724326),
 'great': np.float64(4.526360524616162),
 'greatest': np.float64(4.931825632724326),
 'greed': np.float64(4.931825632724326),
 'greenwich': np.float64(4.931825632724326),
 'grip': np.float64(4.931825632724326),
 'group': np.float64(4.526360524616162),
 'guard': np.float64(4.931825632724326),
 'guerrilla': np.float64(4.931825632724326),
 'gun': np.float64(4.931825632724326),
 'ha': np.float64(3.545531271604435),

In [17]:
## Get Distil Bert Embeddings and combine tfidf with bert embeddings
def sentence_embedding(sentence, model, tokenizer, word2tfidf):
    tokens = tokenizer.tokenize(sentence)
    input_ids = tokenizer.encode(sentence, return_tensors="pt", truncation=True, max_length=512)

    with torch.no_grad():
        outputs = model(input_ids)
    
    word_embeddings = outputs.last_hidden_state.squeeze(0)[1:-1]  # Ignore [CLS] and [SEP]
    embeddings = []
    
    for i, word in enumerate(tokens):
        if word in word2tfidf:  
            weight = word2tfidf.get(word, 1.0)
            embeddings.append(word_embeddings[i] * weight)
    
    if embeddings:
        return torch.mean(torch.stack(embeddings), dim=0).numpy()
    else:
        return np.zeros(model.config.hidden_size)

In [18]:
document_embeddings = np.array([sentence_embedding(sent, model, tokenizer, word2tfidf) for sent in df['description_final'].to_list()])

In [21]:
document_embeddings.shape

(100, 768)

:

In [19]:
query_embeddings = np.array([sentence_embedding(search_sentence_final, model, tokenizer, word2tfidf)])

In [20]:
query_embeddings.shape

(1, 768)

## Inference

In [21]:
## function to calculate cosine distance, larger the value smaller the angle and hence greater the similarity
def similarity(x,y):
    cos = np.dot(x,y)
    res = cos/(np.linalg.norm(x)*np.linalg.norm(y))
    return res.item()

In [22]:
res = []
for emb in document_embeddings:
    res.append(similarity(query_embeddings,emb))

In [23]:
df['similarity'] = res

In [24]:
df.sample(5)

,rank,title,description,image,big_image,genre,thumbnail,rating,id,year,imdbid,imdb_link,description_2,description_final,similarity
0,1,The Shawshank Redemption,Two imprisoned men bond over a number of years...,https://m.media-amazon.com/images/M/MV5BMDFkYT...,https://m.media-amazon.com/images/M/MV5BMDFkYT...,['Drama'],https://m.media-amazon.com/images/M/MV5BMDFkYT...,9.3,top1,1994,tt0111161,https://www.imdb.com/title/tt0111161,Two imprisoned men bond over a number of years...,"two imprison men bond over a number of years, ...",0.765464
27,28,The Green Mile,The lives of guards on Death Row are affected ...,https://m.media-amazon.com/images/M/MV5BMTUxMz...,https://m.media-amazon.com/images/M/MV5BMTUxMz...,"['Crime', 'Drama', 'Fantasy']",https://m.media-amazon.com/images/M/MV5BMTUxMz...,8.6,top28,1999,tt0120689,https://www.imdb.com/title/tt0120689,The lives of guards on Death Row are affected ...,the live of guard on death row are affect by o...,0.764650
68,69,Inglourious Basterds,"In Nazi-occupied France during World War II, a...",https://m.media-amazon.com/images/M/MV5BOTJiND...,https://m.media-amazon.com/images/M/MV5BOTJiND...,"['Adventure', 'Drama', 'War']",https://m.media-amazon.com/images/M/MV5BOTJiND...,8.4,top69,2009,tt0361748,https://www.imdb.com/title/tt0361748,"In Nazi-occupied France during World War II, a...","in nazi-occupi franc dure world war ii, a plan...",0.756069
81,82,Come and See,"After finding an old rifle, a young boy joins ...",https://m.media-amazon.com/images/M/MV5BODM4Nj...,https://m.media-amazon.com/images/M/MV5BODM4Nj...,"['Drama', 'Thriller', 'War']",https://m.media-amazon.com/images/M/MV5BODM4Nj...,8.4,top82,1985,tt0091251,https://www.imdb.com/title/tt0091251,"After finding an old rifle, a young boy joins ...","after find an old rifle, a young boy join the ...",0.762214
55,56,Apocalypse Now,A U.S. Army officer serving in Vietnam is task...,https://m.media-amazon.com/images/M/MV5BYmQyNT...,https://m.media-amazon.com/images/M/MV5BYmQyNT...,"['Drama', 'Mystery', 'War']",https://m.media-amazon.com/images/M/MV5BYmQyNT...,8.4,top56,1979,tt0078788,https://www.imdb.com/title/tt0078788,A U.S. Army officer serving in Vietnam is task...,a u.s. armi offic serv in vietnam is task with...,0.763500

In [33]:
sim_arg_k = np.argsort(res)[-top_k_matches:][::-1]

In [34]:
sim_arg_k

array([94, 49, 78, 53, 77])

In [35]:
## Final Output
df.iloc[sim_arg_k][['title','similarity','description_2']]

,title,similarity,description_2
94,The Hunt,0.852198,"A teacher lives a lonely life, all the while s..."
49,Cinema Paradiso,0.822197,A filmmaker recalls his childhood when falling...
78,3 Idiots,0.821403,Two friends are searching for their long lost ...
53,City Lights,0.817958,"With the aid of a wealthy erratic tippler, a d..."
77,Your Name.,0.815180,Two strangers find themselves linked in a biza...